# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 17:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.SmallIntegerField(choices=[(1, 'Credit'), (2, 'Debit')])),
                ('status', models.SmallIntegerField(choices=[(1, 'Inititated'), (2, 'Completed'), (3, 'Failed'), (4, 'Cancelled')], default=1)),
                ('amount', models.IntegerField(default=0)),
                ('initiated_at', models.DateTimeField(auto_now_add=True, verbose_name='initiated_at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed_at')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled_at')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('added_on', models.DateTimeField(auto_now_add=True, verbose_name='added_on')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'wallet',
                'verbose_name_plural': 'wallets',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.Wallet'),
        ),
    ]
